### PR TITLE
homepage

### PR DESCRIPTION
**Pull request by accursoft**
This change is [Reviewable](https://reviewable.io/reviews/princed/caret/1)

### CODE REVIEW

**Comment by minterior** [comment]
Hello @accursoft. I saw that you deleted your repository https://github.com/accursoft/caret a few days ago (I guess after my PR) and recreated it again, now as a fork from https://github.com/princed/caret. I think you messed things up because you were the original maintainer and the parent repository of all the forks, but now that "role" is for the repository https://github.com/yanickrochon/caret as you can see here: https://github.com/yanickrochon/caret/network/members.

Also with that change you lost some commits that were in your repository but they're not in the @princed's, concretely the ones between the `tag v1.3.1` (9ec5dc14dace9fb17e153dce549fbae6bd57d408) and `Prevent Opera 12 weird bug` (aa691e3ce5374090bbd5dd263defadc0792ca21c).

But don't worry, it is not all lost. It took my time but I managed to have all the commits ready, with the original dates, authors and committers, in my fork https://github.com/Adsmurai/caret. If I were you I would delete your fork, fork it again but now from the current parent repository https://github.com/yanickrochon/caret, then add my fork https://github.com/Adsmurai/caret as a new remote and use its master branch as the good one (at least up to the commit `ignore empty collections` (803c1d104f7369202109df2f7d613b44e1cd87b3). I was very cautious to **keep the original commit hashes** of your original work as well. I also fixed the tags (like the `v1.3.0` pointing to a dead end commit). So here you have the steps:

1. Remove your fork
1. Fork it again from https://github.com/yanickrochon/caret
1. Execute these git commands:
    ```
    git remote add adsmurai git@github.com:Adsmurai/caret.git
    git fetch --all --tags
    git checkout master
    git pull adsmurai master
    git push -f origin master
    git push -f --tags
    ```
1. Add more work on top of the recovered master branch and push it or create a PR to yourself.

That way @princed and me could completely remove our forks because **all** the work will be again on your repository, as the original author and maintainer :smiley: .

If you have any doubt or disagree on something just let me know, I'll be pleased to answer and help on any question. I hope to hear from you soon, kind regards.

**Comment by princed** [comment]
I just wanted to say I'm happy to help in any way, including giving up the package.

**Comment by accursoft** [comment]
@minterior thank you for your assistance, it is much appreciated.

The original repository is actually https://bitbucket.org/accursoft/caret, published at https://www.npmjs.com/package/@accursoft/jquery-caret. I was maintaining a mirror here with hg-git, but it became more trouble than it was worth - so I deleted the mirror, and cherry-picked @princed's fixes.

I don't follow up on all (50!) forks, but this one is published to the npm global namespace (long before I published the scoped original), so I forked it for the sole purpose of updating the links in the published package.json. I plan on deleting it again once this is sorted out.

**Comment by accursoft** [comment]
@princed if you want to continue maintaining your npm package, that's great. If not, maybe redirect it (`npm deprecate`), or transfer and I'll take over.

**Comment by minterior** [comment]
Aha, I understand it better now. Thank you @accursoft for the explanation. In that case, I'm with you: to keep just the original repository in https://bitbucket.org/accursoft/caret and remove the ones in Github to avoid maintainability problems and confusions (like mine). And IMHO the redirect/transfer you told to @princed would be awesome.

I still see a minor problem in [bower.io](): if we search [here](https://bower.io/search/) for `caret`, the first entry points to https://github.com/accursoft/caret.git so if you delete the Github repository again things would break again (that's what happened to us). We already had plans to migrate brom bower to npm, but now we'll do it soon (in a couple of weeks) to use [your one in npm](https://www.npmjs.com/package/@accursoft/jquery-caret). I just mention that because other users could see the same problem.

Cheers.

**Comment by accursoft** [comment]
@minterior good point for bower. I created a fresh mirror of the canonical [BitBucket repository](
https://bitbucket.org/accursoft/caret) at 
https://github.com/accursoft/caret, without the commits that removed bower support.

**Comment by minterior** [comment]
Thank you @accursoft this is a good idea. Nevertheless, our Bower is crashing again because the tags are missing in that new repository: https://github.com/accursoft/caret/tags.
As a final task (hopefully, hehe), could you recreate them, please? Thank you very much.

**Comment by princed** [comment]
@accursoft I gave access to the npm package a couple of days ago. Do I need to do anything else, e.g. merge this PR?

**Comment by accursoft** [comment]
@minterior I've restored the only git tag that I recall - are your builds working now?

**Comment by accursoft** [comment]
@princed I've updated the npm package, thank you.

As for this PR, it really depends on what you want to do with your fork going forward.

**Comment by minterior** [comment]
@accursoft yes, it is working again. Thank you.

**Review by princed — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/princed/caret/1)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by princed** [comment]
I'm closing this one then and closing the repo in favor of https://bitbucket.org/accursoft/caret

**Pull request closed without merging**
